spring.application.name=asesoria

# Conexión a la Base de Datos (Preparado para la Nube)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/novel_asesoria}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:expo2026}

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true